# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11324360670113c3e3c1623dc21379aca1da57b327151c045368b66f52eea0434447786296a1e376e9f8aa15e2c29bf5ad02fca466462b3ba212683892858188

test:
  secret_key_base: a45d77d16f2cae1f2f930459133d08e72a7ba560ff71ec15fde43ca38929c94d1731cf702c11290b2c4695b048c0f8ec57c55688c3c2521e17d17a56bf119866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
